### ISSUE TITLE
Push out eksctl 0.17.0 and 0.18.0

### ISSUE THREAD

**Issue by ChipWolf** [abdennour/dockerfiles#1]
Upstream pushed out a fix (weaveworks/eksctl#2002) and tagged it as part of 0.17.0 for managed node groups not deploying after behavior was changed by AWS on April 22nd

Could we please track the upstream tags for changes to this tool so the containers are in sync?

Thanks

**Comment by abdennour** [comment]
Hello @ChipWolf  , 
Many versions have been released after version 0.16.0 like :

- docker pull abdennour/eksctl:0.22.0-aws-1.18.89-kubectl-v1.18.5
- docker pull abdennour/eksctl:0.19.0-aws-1.18.66-kubectl-v1.18.3
- docker pull abdennour/eksctl:0.19.0-aws-1.18.65-kubectl-v1.18.3
- docker pull abdennour/eksctl:0.19.0-aws-1.18.64-kubectl-v1.18.3
- docker pull abdennour/eksctl:0.18.0-aws-1.18.53-kubectl-v1.18.2

REFERENCE: https://hub.docker.com/r/abdennour/eksctl/tags
